#!/bin/bash
# Update package list and install Nginx if it's not already installed
sudo apt update
sudo apt install -y nginx

# Create a new configuration file for the redirection
echo '
server {
    listen 80;

    # Using the hostname as the server name
    server_name 806472-web-01;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
' | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Enable the new configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration for errors
sudo nginx -t

# Restart Nginx to apply the changes
sudo systemctl restart nginx
