#!/usr/bin/env bash
# This script ensures Nginx is installed, running, and listening on port 80
apt-get update -y && apt-get install -y nginx
service nginx start
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
