#!/usr/bin/env bash
# Get the PID of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# Check if the process is running and kill it
if [ -n "$pid" ]; then
    kill -9 "$pid"
else
    echo "Process 7-highlander not running."
fi
