#!/usr/bin/env bash
# This script displays "Best School" 10 times, and "Hi" on the 9th iteration
num=1
while [ $num -le 10 ]
do
  if [ $num -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  num=$((num + 1))
done
