#!/usr/bin/env bash
# This script loops from 1 to 10 with special messages for the 4th and 8th iterations
num=1
while [ $num -le 10 ]
do
  if [ $num -eq 4 ]; then
    echo "bad luck"
  elif [ $num -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  num=$((num + 1))
done
