#!/usr/bin/env bash
# Script to configure localhost and facebook.com IPs

# Backup the current /etc/hosts file
cp /etc/hosts ~/hostsOmar

# Modify localhost and facebook.com IP entries
echo "127.0.0.2		localhost" > ~/hostsOmar
echo "8.8.8.8		facebook.com" >> ~/hostsOmar

# Replace the original /etc/hosts file with the new one
cp -f ~/hostsOmar /etc/hosts
