#!/usr/bin/env bash
#Change Nginx user to nginx
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80;/listen \[::\]:8080;/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /var/www/html
service nginx restart
